-intstyle "ise" -incremental -lib "secureip" -o "/home/developer/Proyectos/xilinx/ControlUnit/main_tb_isim_beh.exe" -prj "/home/developer/Proyectos/xilinx/ControlUnit/main_tb_beh.prj" "work.main_tb" 
